/**
 * PLANT DATA LIBRARY
 *
 * This library provides access to plant data from the local plants.json file.
 * It uses the localPlantData module for data access.
 *
 * The plants.json file is the authoritative source, generated by:
 * 1. scripts/fetch-perenual.ts - Fetches data from Perenual API
 * 2. scripts/fetch-aspca-toxicity.ts - Fetches ASPCA toxicity data
 * 3. scripts/build-master-plant-list.ts - Merges all data sources
 */

import { Plant, PlantFilters } from '@/types/plant';
import * as localPlantData from '@/lib/localPlantData';

/**
 * Get plants suitable for a specific USDA hardiness zone
 */
export async function getPlantsForZone(zone: number): Promise<Plant[]> {
  return localPlantData.getPlantsForZone(zone);
}

/**
 * Get a single plant by ID
 */
export async function getPlantById(id: string): Promise<Plant | null> {
  return localPlantData.getPlantById(id);
}

/**
 * Get all plants (optionally filtered)
 */
export async function getAllPlants(filters?: PlantFilters): Promise<Plant[]> {
  return localPlantData.getAllPlants(filters);
}

/**
 * Filter plants based on criteria
 */
export function filterPlants(plants: Plant[], filters: PlantFilters): Plant[] {
  return localPlantData.filterPlants(plants, filters);
}

/**
 * Get curated starter plants for a specific zone
 */
export async function getCuratedPlantsForZone(zone: number): Promise<Plant[]> {
  return localPlantData.getCuratedPlantsForZone(zone);
}
